# Generated by Django 3.1.2 on 2021-01-09 05:51

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('body', models.TextField(max_length=60000)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=dashboard.models.upload_location)),
                ('extra_image_one', models.ImageField(blank=True, null=True, upload_to=dashboard.models.upload_location)),
                ('extra_image_two', models.ImageField(blank=True, null=True, upload_to=dashboard.models.upload_location)),
                ('extra_image_three', models.ImageField(blank=True, null=True, upload_to=dashboard.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_approved', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewed_by', models.ManyToManyField(related_name='announcement_post_viewed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
