# Generated by Django 3.1.2 on 2020-12-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicpost',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
