# Generated by Django 3.1.2 on 2020-10-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20201018_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
