# Generated by Django 3.1.2 on 2020-11-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_customcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicpost',
            name='category',
            field=models.CharField(choices=[('GCD', 'General Car Discussion'), ('CA', 'Car Accessories'), ('CP', 'Car Performance Parts'), ('CC', 'Continental Cars'), ('CEI', 'Cosmetic Enhancement Items'), ('ICE', 'In Car Entertainment'), ('JC', 'Japanese Cars'), ('MR', 'Maintenance & Repairs'), ('TR', 'Tyres & Rims'), ('O', 'NON CAR-RELATED')], default='O', max_length=5),
        ),
    ]
