# Generated by Django 3.1.2 on 2020-11-10 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(choices=[('AWWW', 'A Way With Words'), ('DS', 'Discussion Starter'), ('CEL', 'Celebrity'), ('TU', 'Thumbs Up'), ('NM', 'NEW MEMBER')], default='NM', max_length=6)),
                ('level', models.PositiveIntegerField(max_length=2)),
                ('viewed_by_user', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
