# Generated by Django 3.1.2 on 2020-11-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementpost',
            name='level',
            field=models.PositiveIntegerField(),
        ),
    ]
