# Generated by Django 3.1.2 on 2020-11-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_auto_20201110_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementpost',
            name='slug',
        ),
        migrations.AlterField(
            model_name='achievementpost',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
