# Generated by Django 3.1.2 on 2020-11-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_key', models.CharField(max_length=200)),
                ('log_value', models.TextField(max_length=5000)),
                ('log_type', models.CharField(choices=[('D', 'DEBUG'), ('E', 'ERROR'), ('I', 'INFO')], default='I', max_length=1)),
                ('date_logged', models.DateTimeField(auto_now_add=True, verbose_name='date logged')),
                ('resolved', models.BooleanField(default=True)),
            ],
        ),
    ]
