# Generated by Django 3.1.2 on 2020-11-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_analytics', '0002_forumanalytics_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumanalytics',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
